apiVersion: apps/v1
kind: Deployment
metadata: 
    name: nginx-deployment-example
spec:
    selector:
        matchLabels:
            app: nginx-deployment-example
    replicas: 2
    template:
        metadata:
            labels:
                app: nginx-deployment-example
        spec:
            containers:
              - name: nginx-deployment-example
                image: nginx:1.19.2-alpine
                ports:
                    - containerPort: 80
                volumeMounts:
                    - mountPath: /etc/nginx/conf.d
                      name: nginx-conf
                      readOnly: true
            volumes:
                - name: nginx-conf
                  configMap:
                    name: nginx-conf
                    items:
                        - key: nginx.conf
                          path: nginx.conf

                
